### ISSUE TITLE
gbm CLI checklist includes clear directions

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/release-toolkit-gutenberg-mobile#139]
Currently, when generating a release checklist with the [`gbm` CLI](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/compare/gbm-cli?expand=1), there are a few typos, missing syntax parsing, or unnecessary conditional statements. We could address these to improve clarity.   

```[tasklist]
### Tasks
- [x] Update notice channel for infrastructure team (i.e. reapply #141)
- [ ] https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/issues/147
- [x] Ensure Markdown code syntax is parsed. Replace usage of a separate Quote block with task text separated from task description by two new lines.
- [x] Given the template now adapts to the typeof release, we can remove the conditional prefix for tasks.
- [x] Repair the GitHub Release link to include the required .0 in the release, tag, and branch names.
- [x] Copy changes from https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/143
```

| Screenshot | Action |
| - | - |
| ![missed-interpolation](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/438664/26154429-238c-4dbe-ac62-488a4ef15038) | Fix interpolation to display correct version number without extraneous characters. |
| ![missed-syntax-parsing](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/438664/d53e79c2-4aed-4b5f-b47d-b3a554813387) | Ensure Markdown code syntax is parsed. Replace usage of a separate Quote block with task text separated from task description by two new lines. |
| ![unnecessary-conditional-statement](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/438664/4ab32152-fce6-4462-865a-eaeb04e81f2b) | Given the template now adapts to the typeof release, we can remove the conditional prefix for tasks. | 
| ![missing-zero-in-url](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/438664/1d3e9a19-e78c-4091-bcd9-38cad75c32a3) | Repair the GitHub Release link to include the required `.0` in the release, tag, and branch names. |

**Comment by jhnstn** [comment]
I believe most of the issues here were related to[ this](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/issues/137#issuecomment-1739592848)

I've expanded the version verification to ensure there is always a patch value, even for `.0`. This seemed like the most efficient way to avoid surprises. I also don't think it's too much effort to type out the full release version.

The other issues were resolved in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/146
